version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
      - mkdir -p build/subdir_build
      - touch build/subdir_build/build.txt
      - echo $CODEBUILD_SRC_DIR >> build/subdir_build/build.txt
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/aws-build-sample-maven-project-0.0.1-SNAPSHOT.jar
    - build/**/*
